### ISSUE TITLE
Show the correctly guessed word in the '_' area

### ISSUE THREAD

**Issue by akrastev** [akrastev/hangman#4]
At 50e9efca658468fdae1e911a2a58d817ccee320b.

|- - |
|    |
|   / \
|   \ /
|    |
|

The guess so far:   r e i n _ e n t o r    (10 letters)
Right guesses: etinor
Wrong guesses: ulmps
Guess a letter: v
Got it. Guess: v
YOU ROCK!
The word was: reinventor

> The guess so far:   r e i n _ e n t o r    (10 letters)
Edit that to show the correctly guessed word instead of writing below "The word was: reinventor".

While at it, remove the "The guess so far: " and add a new line after "letters)"

**Comment by akrastev** [comment]
Thanks @ZombineDev for the suggestion!

**Comment by PetarKirov** [comment]
Nice work :stuck_out_tongue:
